### ISSUE TITLE
FileNotFoundException When Copying Save Data

### ISSUE THREAD

**Issue by EverGreenTaiga** [iamvishnu-media/Apex-Launcher#39]
![help_plz](https://user-images.githubusercontent.com/78122781/106074883-a0b0a400-60da-11eb-9835-42c1eee238d5.PNG)

Hi all,

So I'm just trying to copy my save file in the launcher and I keep getting this error when I highlight the current save (the save in question) and pressing the copy button. I have no idea what's causing this because when I go to the location the launcher is having a problem with, a file called Game.rxdata is right there! When I try to rename the file to ApexGame.rxdata, the same issue occurs but is now looking for a nonexistent file called ApexApexGame.rxdata! How do I fix this?!
P.S: The blue thing that's scribbled out is just the user's name which I don't want to reveal.

**Comment by iamvishnu-media** [comment]
This looks like an issue with how the file path is being processed. There should be a backslash between `Pokemon Apex` and `Game.rxdata`. I should be able to fix this easily.

In the future, the contents of the Details dropdown are often extremely helpful in getting to the source of the issue, as it will often tell me the exact line of code that's causing the error.

**Comment by iamvishnu-media** [comment]
Should be fixed as of linked commit, and will be patched in the next launcher version. Thank you for reporting.

**Comment by EverGreenTaiga** [comment]
Nope, still getting the same error unfortunately... Here's what appears when clicking details:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\<user's name>\Saved Games\Pokémon ApexGame.rxdata'.
File name: 'C:\Users\<user's name>\Saved Games\Pokémon ApexGame.rxdata'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ApexLauncher.SaveManagementForm.CopyButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Apex Launcher
    Assembly Version: 1.6.1.0
    Win32 Version: 1.6.1.0
    CodeBase: file:///C:/Users/<user's name>/Desktop/Pokemon%20RPG%20Maker%20Games/Pokemon%20Apex/Apex.Launcher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by iamvishnu-media** [comment]
Right, it hasn't been patched yet. You'll have to wait until the next Launcher release (or compile it yourself I guess)
